static const char base[] = "#191724";
static const char text[] = "#e0def4";    // text
static const char overlay[] = "#26233a"; // unfocused window border
static const char muted[] = "#6e6a86";
static const char subtle[] = "#908caa";
static const char foam[] = "#9ccfd8"; // focused window border
static const char iris[] = "#c4a7e7";
static const char pine[] = "#31748f";
static const char love[] = "#eb6f92";
static const char rose[] = "#ebbcba";
static const char gold[] = "#f6c177";
