static const char black[]       = "#24283b";
static const char white[]       = "#c0caf5"; // text
static const char gray2[]       = "#232433"; // unfocused window border
static const char gray3[]       = "#2a2b3d";
static const char gray4[]       = "#32344a";
static const char cyan[]        = "#7dcfff";
static const char blue[]        = "#7AA2F7";  // focused window border
static const char magenta[]     = "#bb9af7";
static const char green[]       = "#9ECE6A";
static const char teal[]        = "#1abc9c";
static const char red[]         = "#F7768E";
static const char orange[]      = "#FF9E64";
static const char yellow[]      = "#E0AF68";
static const char purple[]        = "#9d7cd8";
static const char col_borderbar[]  = "#1f2335"; // inner border
