static const char bg[] = "#1a1b26";
static const char fg[] = "#c0caf5";    // text
static const char gray2[] = "#292e42"; // unfocused window border
static const char gray3[] = "#3b4261";
static const char gray4[] = "#545c7e";
static const char cyan[] = "#7dcfff";
static const char blue[] = "#7aa2f7"; // focused window border
static const char blue0[] = "#3d59a1";
static const char blue1[] = "#2ac3de";
static const char blue2[] = "#0db9d7";
static const char blue5[] = "#89ddff";
static const char blue6[] = "#b4f9f8";
static const char blue7[] = "#394b70";
static const char magenta[] = "#bb9af7";
static const char magenta2[] = "#ff007c";
static const char purple[] = "#9d7cd8";
static const char orange[] = "#ff9e64";
static const char yellow[] = "#e0af68";
static const char green[] = "#9ece6a";
static const char green1[] = "#73daca";
static const char green2[] = "#41a6b5";
static const char teal[] = "#1abc9c";
static const char red[] = "#f7768e";
static const char red1[] = "#db4b4b";
